# Generated by Django 4.2.5 on 2023-10-08 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exames', '0003_alter_acessomedico_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacaoexame',
            name='senha',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
